l_english:
  add_artificery_title:0 "Institutionalize Artificery"
  add_artificery_desc:0 "The advancements of artificery have been undeniable. It is time we embrace these benefits nationwide and fund the projects ourselves."
  strong_empire:0 "A Strong Empire"
  strong_empire_desc:0 "We are leading a strong and united Empire."