l_english:
 kvaszbennar_colonize:0 "Colonial Investments"
 extra_colonial_title:0 "Funds for Colonial Efforts"
 extra_colonial_desc:0 "We like sending people overseas into uncharted lands. Fun!"
 give_up_hegemony_title:0 "Surrender Our Hegemony"
 give_up_hegemony_desc:0 "Every Empire must fall sooner or later. Our time has finally come."